# Crear un programa que pida al usuario ingresar dos números y calcule su suma, resta, multiplicación y
división.

print("Ingrese el primer número: ")
num1 = int(input())
print("Ingrese el segundo número: ")
num2 = int(input())

suma = num1 + num2
resta = num1 - num2
multiplicacion = num1 * num2
division = num1 / num2

print("La suma es:", suma)
print("La resta es:", resta)
print("La multiplicación es:", multiplicacion)
print("La división es:", division)
